// canditech/src/app/Layout.vue
<template>
  <nav class="fixed top-0 z-50 w-full border-b border-base-300">
    <div class="px-3 py-3 lg:px-5 lg:pl-3">
      <div class="flex items-center justify-end">
        <div class="flex items-center ml-3">
          <slot name="nav-menu" />
        </div>
      </div>
    </div>
  </nav>

  <div class="p-5 pt-16 sm:pt-12">
    <slot></slot>
  </div>
</template>

// components/layout.tsx
import { Inter } from "@next/font/google";
import clsx from "clsx";

const inter = Inter({ subsets: ["latin"] });

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <main className={clsx("flex h-screen flex-col", inter.className)}>
      <nav className="fixed top-0 z-50 w-full border-b border-base-300">
        <div className="px-3 py-3 lg:px-5">
          <div className="flex items-center justify-end">Navbar</div>
        </div>
      </nav>
      <div className="pt-16 flex-1 container mx-auto">{children}</div>
    </main>
  );
}
